### ISSUE TITLE
Setup validators

### ISSUE THREAD

**Issue by zhammer** [zhammer/morning-cd#105]
As per discussion with evan, invalidator can look something like:

```py
def submit_listen(listen_input: ListenInput):
    invalid_reason = listen_entity.check_invalid
    if invalid_reason:
        # handle invalid
    ...
```

(I guess this is where https://www.python.org/dev/peps/pep-0572/ would be nice)

**Comment by zhammer** [comment]
@evanhammer do you have a reference to where you read about this pattern? functional programming invalidation standards or something?

**Comment by zhammer** [comment]
This should be it for validators at the moment

**Comment by evanhammer** [comment]
Yes, I have examples, though they are not functional:

(in order of popularity)

1. https://github.com/chriso/validator.js
* If no error, `isConstraint` returns true. EBH: But this library only validates a single field against a single constraint. 

2. https://validatejs.org/
* If there are no errors nothing is returned. Otherwise an object in this format is returned.

3. https://github.com/eivindfjeldstad/validate
* The .validate() function returns an array of validation errors. (EBH: Unclear what happens when no errors. I think it returns an empty array.)

I also looked into Folktale (a functional library of data structures) and its Validation object: https://folktale.origamitower.com/api/v2.3.0/en/folktale.validation.html
* Looks like it's type is either `Success` or `Failure`. Success has the original value. And Failure has an array of errors.
